# Generated by Django 5.1.4 on 2026-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(blank=True, max_length=150, verbose_name='Реферер')),
                ('origin_link', models.URLField(verbose_name='Оригинальная ссылка')),
                ('promo_link', models.CharField(max_length=20, unique=True, verbose_name='Промо ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ссылки')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='Количество кликов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность ссылки')),
            ],
            options={
                'verbose_name': 'Промо ссылка',
                'verbose_name_plural': 'Промо ссылки',
                'ordering': ('-created_at',),
            },
        ),
    ]
