# Generated by Django 5.1.4 on 2026-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promolink',
            name='promo_title',
            field=models.CharField(default='', max_length=150, verbose_name='Промо заголовок'),
        ),
        migrations.AlterField(
            model_name='promolink',
            name='promo_link',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Промо ссылка'),
        ),
    ]
