# Generated by Django 5.1.4 on 2026-08-28 10:21


import uuid

from django.db import migrations


def generate_access_token(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        while True:
            new_token = uuid.uuid4()
            if not User.objects.filter(access_token=new_token).exists():
                user.access_token = new_token
                break
        user.save(update_fields=["access_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_access_token"),
    ]

    operations = [
        migrations.RunPython(
            generate_access_token, reverse_code=migrations.RunPython.noop
        ),
    ]
