# Generated by Django 5.1.4 on 2026-08-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер бокса')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь, м²')),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Длина, м')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ширина, м')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Высота, м')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена в месяц, ₽')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занят')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('feature', models.CharField(blank=True, max_length=200, verbose_name='Особенность')),
                ('image', models.ImageField(blank=True, upload_to='warehouses/', verbose_name='Фото склада')),
                ('price_per_square_meter', models.PositiveIntegerField(verbose_name='Цена за м² в месяц, ₽')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за месяц (на момент аренды)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='active', max_length=20)),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='storage.box', verbose_name='Бокс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователб')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.warehouse'),
        ),
    ]
