# Generated by Django 5.1.4 on 2026-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Контейнер', 'verbose_name_plural': 'Контейнеры'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Cклад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='temperature',
            field=models.IntegerField(default='18', verbose_name='Температура на складе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Высота, м'),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Длина, м'),
        ),
        migrations.AlterField(
            model_name='box',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена в месяц, ₽'),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Ширина, м'),
        ),
    ]
