# Generated by Django 5.1.4 on 2026-08-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_box_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='contacts',
            field=models.TextField(blank=True, default='', verbose_name='Контакты склада'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание склада'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='route',
            field=models.TextField(blank=True, default='', verbose_name='Как проехать'),
        ),
    ]
